// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_y6cS0s8YQaJ8GhzsG2zwsrmGMvN2_88',
    appId: '1:960178877868:web:762c5b0cf81bf203fa7609',
    messagingSenderId: '960178877868',
    projectId: 'safeauto-97339',
    authDomain: 'safeauto-97339.firebaseapp.com',
    storageBucket: 'safeauto-97339.appspot.com',
    measurementId: 'G-7WM96K0Q83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADy5eobd-DdfuYoaiseE3iVFol24I5GMQ',
    appId: '1:960178877868:android:e57f6a14600f403dfa7609',
    messagingSenderId: '960178877868',
    projectId: 'safeauto-97339',
    storageBucket: 'safeauto-97339.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPF8nT8oF06NyhixslLkBW_4uxbT1-yWc',
    appId: '1:960178877868:ios:a285a065b07c8f24fa7609',
    messagingSenderId: '960178877868',
    projectId: 'safeauto-97339',
    storageBucket: 'safeauto-97339.appspot.com',
    iosBundleId: 'com.example.safeauto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPF8nT8oF06NyhixslLkBW_4uxbT1-yWc',
    appId: '1:960178877868:ios:a285a065b07c8f24fa7609',
    messagingSenderId: '960178877868',
    projectId: 'safeauto-97339',
    storageBucket: 'safeauto-97339.appspot.com',
    iosBundleId: 'com.example.safeauto',
  );
}
